### PR TITLE
Added magic-wand icon

### PR DESCRIPTION
**Pull request by manpreetnarang**

### CODE REVIEW

**Comment by makeready** [comment]
Non blocker: We probably dont need to serve all those different font file types. `.woff2` files are compatible in all supported browsers

**Comment by makeready** [comment]
Can you please show a screenshot of the new icon in line with some of the existing icons? That way we can review the alignment and spacing of the new glyph

**Comment by manpreetnarang** [comment]
image


> Can you please show a screenshot of the new icon in line with some of the existing icons? That way we can review the alignment and spacing of the new glyph

**Comment by makeready** [comment]
> image

That storybook is a good reference to know what icons we have but unfortunately it's not very useful for evaluating alignment and sizing. A screenshot with the icons as `inline` elements  is the best way

**Comment by manpreetnarang** [comment]
> Non blocker: We probably dont need to serve all those different font file types. `.woff2` files are compatible in all supported browsers

We are only using 2 of these font types. `ttf` and `woff` which should cover most of the browsers.

**Review by makeready — APPROVED** [review]

**Pull request merged**
